effective-dev-opensource/Effective-Office

tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/di/view_models/AutoplayViewModule.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/autoplay/AutoplayScreen.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/autoplay/AutoplayViewModel.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/autoplayMenu/AutoplayMenuScreen.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/autoplayMenu/component/SelectableMenuItem.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/menu/MenuScreen.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/menu/component/ButtonAutoplay.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/menu/component/MenuComponent.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/menu/component/MenuItems.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/navigation/NavigationHost.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/navigation/NavigationModel.kt
Design menu for set up autoplay
=> Autoplay menu

tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/domain/model/Resource.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/domain/model/synology/PhotoDomain.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/network/synology/SynologyApi.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/network/synology/models/response/SynologyAlbumsResponse.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/network/synology/models/response/SynologyPhotoSAlbumsResponse.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/network/use_cases/PhotoSynologyUseCase.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/repository/synology/PhotoSynologyRepository.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/repository/synology/SynologyRepository.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/repository/synology/impl/PhotoSynologyRepositoryImpl.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/repository/synology/impl/SynologyRepositoryImpl.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/menu/component/TimeComponent.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/photo/PhotoViewModel.kt, tv-app/effecticeTV/app/src/main/java/band/effective/office/tv/screen/photo/components/PhotoUI.kt
Old requests work with file station api. Now app supported synology photo api
=> Add new requests for synology photo api

effectiveOfficeBackend/build.gradle.kts, effectiveOfficeBackend/gradle.properties
=> ktorm dependencies

composeApp/composeApp.podspec, composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/ElevatorUpButton.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/TitlePage.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/MainScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/ElevatorUIComponent.kt, composeApp/src/commonMain/resources/MR/base/strings_ru.xml, composeApp/src/commonMain/resources/MR/en/strings_en.xml
Updated the appearance of the main screen in accordance with the new design.
=> Updated main screen

effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/converters/UserDTOModelConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/di/userDIModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/repository/UserRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/routing/AuthRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/service/UserService.kt
Fix of user dto->model converter behavior, also fixed user update
=> Backend app/feature/user

effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/di/userDIModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/facade/UserFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/routes/AuthRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/routes/userRouting.kt
Creates facade to use transactionManager without service changes
=> TransactionManager usage for UserService

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/TabNavigationItem.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/content/Content.kt
[~] refactoring code to fit design
=> Refactoring bottom tab

effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/converters/IntegrationDTOModelConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/dto/IntegrationDTO.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/repository/UserIntegrationEntity.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/repository/UserRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/routes/swagger/UserSwagger.kt
Now user able to update integrations
=> Integrations update 

hs_err_pid6088.log, replay_pid6088.log, tabletApp/features/core/src/commonMain/kotlin/band/effective/office/tablet/ui/theme/Theme.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/FreeNegotiationsScreen.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/roomUiState/RoomUiState.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/store/FreeNegotiationsStore.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/store/FreeNegotiationsStoreFactory.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/uiComponents/LoaderView.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/uiComponents/getDuration.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/kotlin/band/effective/office/tablet/ui/freeNegotiationsScreen/ui/freeNegotiationsScreen/uiComponents/roomCard/StateRoomView.kt, tabletApp/features/freeNegotiationsScreen/src/commonMain/libres/strings/strings_ru.xml, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/api/WorkApi.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/RoomRepositoryImpl.kt
Added:
1. loading to screen booking other room
2. get data about rooms from work api
3. room status update after time out
=> Update room state

effectiveOfficeBackend/gradle.properties, effectiveOfficeBackend/src/main/kotlin/office/effective/common/exception/InstanceNotFoundException.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/common/exception/ValidationException.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/common/exception/WorkspaceUnavailableException.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/common/utils/DatabaseTransactionManager.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/common/utils/UuidValidator.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/config/BookingDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/BookingFacadeConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/BookingRepositoryConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/facade/BookingFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/BookingRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/BookingRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/swagger/BookingSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/service/BookingService.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/config/WorkspaceDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/converters/WorkspaceFacadeConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/converters/WorkspaceRepositoryConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/facade/WorkspaceFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/routes/WorkspaceRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/routes/swagger/WorkspaceSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/service/WorkspaceService.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/RequestValidation.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/StatusPages.kt, effectiveOfficeBackend/src/main/resources/application.conf, effectiveOfficeBackend/src/test/kotlin/office/effective/TestUuidValidator.kt, effectiveOfficeBackend/src/test/kotlin/office/effective/booking/BookingFacadeTest.kt, effectiveOfficeBackend/src/test/kotlin/office/effective/workspace/WorkspaceFacadeTest.kt
Add swagger documentation for booking routes.
Workspace and booking id are now optional parameters to get all bookings.
Add checking whether the workspace is available for booking.
Fix bug.
Add javadoc commets for all methods.
Add tests for bookingFacade.
Change logback version
=> Booking fix

effectiveOfficeBackend/src/main/resources/changelog/changelog-1.0.yaml, effectiveOfficeBackend/src/main/resources/changelog/changelog-1.2.yaml, effectiveOfficeBackend/src/main/resources/changelog/changelog-1.6.yaml, effectiveOfficeBackend/src/main/resources/changelog/changelog-master.yaml
api keys and workspace zones tables
=> Backend app/feature/new tables

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/TabNavigationItem.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_google/AuthorizationGoogleScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/components/BookingCardUser.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/store/AboutEmployeeStoreFactory.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/BookingCard.kt, composeApp/src/commonMain/resources/MR/base/strings_ru.xml, composeApp/src/commonMain/resources/MR/en/strings_en.xml
Replased text in placeholders in authorization screen
Changed Booking card on main screen according lates design
On main screen replased "Ваши ближайшие брони" with "брони"
=> Mabile app/feature/fixes UI

effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/swagger/BookingSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/converters/WorkspaceFacadeConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/converters/WorkspaceRepositoryConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/dto/WorkspaceDTO.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/dto/WorkspaceZoneDTO.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/facade/WorkspaceFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceEntity.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceZoneEntity.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/routes/WorkspaceRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/routes/swagger/WorkspaceSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/service/WorkspaceService.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/model/Workspace.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/model/WorkspaceZone.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/RequestValidation.kt
Add request returning all free workspaces by period and tag
Add workspace zones
Add request returning all zones
More readable swagger code
Fix booking validation
=> Backend app/feature/zones and free workspaces request

effectiveOfficeBackend/docker-compose.yml, effectiveOfficeBackend/src/main/kotlin/office/effective/common/utils/commonDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/Migration.kt
Ktor conf file didn't resolve env variables at run time, only bypassing they names into code. Hence for a while config variables resolution was replaced with std System.getenv env resolution.
=> Added environment variables resolution, avoiding ktor conf file

.github/workflows/backend-build.yaml
Implemented github action for build and distribute backend docker images
=> Added backend Dockerfile build and push on registries action

contract/src/commonMain/kotlin/band/effective/office/network/api/Api.kt, contract/src/commonMain/kotlin/band/effective/office/network/api/impl/ApiImpl.kt, contract/src/commonMain/kotlin/band/effective/office/network/api/impl/ApiMock.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/BookingDTO.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/IntegrationDTO.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/UserDTO.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/UtilityDTO.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/WorkspaceDTO.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/WorkspaceZoneDTO.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/RoomRepositoryImpl.kt
Change dto files to actual version of backend dto
=> Сhange dto

.github/workflows/backend-build.yaml
Migrations now run after the image build
=> Added migrations job after build backend

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/Calendar.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/utils/ConvertDate.kt
- add formatter for date in calendar 
- add ru-localization for month
=> add RU-localization for month in calendar

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/BookingScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/BookingCard.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/OptionMenu.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/modals/ChooseZone.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/models/MockDataSpaces.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt, composeApp/src/commonMain/resources/MR/base/strings_ru.xml
Fixed bug sorting by zones,
Messed up buttons fixed,
Added Call box in rooms.
=> Fixed bug sorting by zones

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/bottomSheet/MultiBottomSheetController.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/MockBookingRepositoryImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/modals/BookAccept.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt, modal_custom_dialog/src/commonMain/kotlin/effective/office/modalcustomdialog/Dialog.kt
Fix open/close functions for BottomSheets in Booking
=> fix BottomSheets

contract/src/commonMain/kotlin/band/effective/office/network/api/Api.kt, contract/src/commonMain/kotlin/band/effective/office/network/api/impl/ApiImpl.kt, contract/src/commonMain/kotlin/band/effective/office/network/api/impl/ApiMock.kt, contract/src/commonMain/kotlin/band/effective/office/network/dto/SuccessResponse.kt, contract/src/commonMain/kotlin/band/effective/office/utils/KtorEitherPlagin.kt, contract/src/commonMain/kotlin/band/effective/office/utils/KtorEtherClient.kt, contract/src/commonMain/kotlin/band/effective/office/utils/MockFactory.kt, tabletApp/features/domain/src/commonMain/kotlin/band/effective/office/tablet/domain/useCase/BookingUseCase.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/RoomRepository.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/BookingRepositoryImpl.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/CancelRepositoryImpl.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/OrganizerRepositoryImpl.kt, tabletApp/features/network/src/commonMain/kotlin/band/effective/office/tablet/network/repository/impl/RoomRepositoryImpl.kt, tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/mainScreen/MainScreenView.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/updateEvent/UpdateEventView.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/updateEvent/store/UpdateEventStore.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/updateEvent/store/UpdateEventStoreFactory.kt
Hotfix tablet application after connect with server
=> hotfix tablet

composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/ProfileRepositoryImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/models/User.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/usecase/GetUserUseCase.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/usecase/UpdateUserUseCase.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/MainScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/ProfileEditScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/store/ProfileEditStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/store/ProfileEditStoreFactory.kt, composeApp/src/commonMain/resources/MR/base/strings_ru.xml, composeApp/src/commonMain/resources/MR/en/strings_en.xml
Profile updates are now coming to the server
=> Profile updates are now coming to the server

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/modals/BookingRepeat.kt
fix select booking end, then input date
=> fix select booking end, then input date

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/BookingScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt
add validation for selected date
=> add validation for selected date

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt
=> Fix date when select all day

composeApp/src/androidMain/kotlin/band/effective/office/elevator/utils/DateFormater.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/BookingScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/components/modals/BookingRepeat.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/models/Frequency.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/booking/store/BookingStoreFactory.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/allEmployee/EmployeeScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/utils/DateFormater.kt, composeApp/src/iosMain/kotlin/band/effective/office/elevator/utils/DateFormater.kt, contract/src/commonMain/kotlin/band/effective/office/network/api/impl/ApiImpl.kt
=> Mobile/final fix UI

effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/RecurrenceRuleFactory.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/model/Recurrence.kt
Fix recurrend ending - until, by changing date-time format to format from rfc5545.
=> Backend fix recurrence until

effectiveOfficeBackend/src/main/kotlin/office/effective/common/constants/BookingConstants.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/di/BookingDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/facade/BookingFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/BookingCalendarRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/BookingRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/IBookingRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/BookingRouting.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/swagger/BookingSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/service/BookingService.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/StatusPages.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/serviceapi/IBookingService.kt
Filtering by booking start in all requests.
Request optimization.
Some requests now return single events.
=> Backend app/hotfix/calendar repository fix

effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/repository/WorkspaceRepository.kt
PR fix ability to find free workspaces
=> [~] rework findAllFreeByPeriod()

composeApp/src/commonMain/kotlin/band/effective/office/elevator/Color.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/ElevatorUpButton.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_phone/AuthorizationPhoneScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_profile/AuthorizationProfileScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_telegram/AuthorizationTelegramScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/MainScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/ElevatorUIComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStoreFactory.kt
Fix bugs:
- removed unnecessary hints
- fix text field color
- change enable elevator button
=> Help with fix

effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/repository/ApiKeyEntity.kt
Fix wrong name of key_value column
=> [~] fix key_value column name

tvApp/src/main/java/band/effective/office/tv/di/NetworkModule.kt, tvApp/src/main/java/band/effective/office/tv/network/notion/EmployeeInfoRemoteDataSourceImpl.kt, tvApp/src/main/java/band/effective/office/tv/repository/duolingo/impl/DuolingoRepositoryImpl.kt, tvApp/src/main/java/band/effective/office/tv/repository/workTogether/Teammate.kt, tvApp/src/main/java/band/effective/office/tv/repository/workTogether/WorkTogether.kt, tvApp/src/main/java/band/effective/office/tv/repository/workTogether/WorkTogetherImpl.kt, tvApp/src/main/java/band/effective/office/tv/screen/components/EventStoryScreenContent.kt, tvApp/src/main/java/band/effective/office/tv/screen/duolingo/components/GirdItem.kt, tvApp/src/main/java/band/effective/office/tv/screen/leaderIdEvents/LeaderIdEventsViewModel.kt, tvApp/src/main/java/band/effective/office/tv/ui/theme/Type.kt
Show name from work together instead of nick from duolingo
=> Name on duolingo screen

effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/TokenVerifier.kt
fix google token verification issue
=> [-] delete .setAudience from builder

buildSrc/buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/buildSrc/src/main/kotlin/Plugins.kt, composeApp/build.gradle.kts, composeApp/composeApp.podspec, composeApp/src/androidMain/kotlin/band/effective/office/elevator/domain/AppActivityLifecycleObserver.kt, gradle.properties, gradle/wrapper/gradle-wrapper.properties, modal_custom_dialog/src/androidMain/AndroidManifest.xml, tabletApp/build.gradle.kts, tabletApp/features/core/build.gradle.kts, tabletApp/features/domain/build.gradle.kts, tabletApp/features/freeNegotiationsScreen/build.gradle.kts, tabletApp/features/network/build.gradle.kts, tabletApp/features/roomInfo/build.gradle.kts, tabletApp/features/selectRoom/build.gradle.kts, wheel-picker-compose/src/androidMain/AndroidManifest.xml
- update compose version to `1.5.2`
- update Kotlin version to `1.9.0`
- update agp version to `8.0.2`
- update grade version to `8.2.1`
- update epic-calendar to `1.0.5`
=> Update compose version

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/UserInfoTextField.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/ProfileRepositoryImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/models/User.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/AuthorizationComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_phone/AuthorizationPhoneScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_phone/store/AuthorizationPhoneStoreImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_profile/AuthorizationProfileScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_profile/store/AuthorizationProfileStoreImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_telegram/AuthorizationTelegramScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_telegram/store/AuthorizationTelegramStoreImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/store/AuthorizationStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/store/AuthorizationStoreImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/models/PhoneMaskTransformation.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/models/UserDataTextFieldType.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/ProfileEditScreen.kt, composeApp/src/commonMain/resources/MR/base/strings_ru.xml
fixed: 
- keyboard options 
- save user data after change
- save user info after auth flow
=> Beta test fix

effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/di/authDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/repository/AuthRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/service/ApiKeyVerifier.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/service/AuthenticationPipeline.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/service/ITokenVerifier.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/service/RequestVerifier.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/simpleAuth/service/TokenVerifier.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/di/userDIModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/user/facade/UserFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/plugins/VerificationPlugin.kt
=> Backend app/hotfix/verification fix

buildSrc/buildSrc/src/main/kotlin/Plugins.kt, composeApp/build.gradle.kts
- update android plugin 
- fix build.gradle.kts mobile module
=> HotFix for build mobile application

tvApp/src/main/res/values/strings.xml
Update welcome to new employees string
=> Fix Welcome Screen

effectiveOfficeBackend/src/main/kotlin/office/effective/model/Recurrence.kt
=> Fix until convertation

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/AboutEmployee.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/MainScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/BookingInformation.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/DateSelection.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStoreFactory.kt
Swipe - to refresh on main screen and minor fixes
=> Swipe - to refresh on main screen 

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/content/ContentComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/ProfileComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/root/RootComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/root/RootContent.kt
Fix navigation, when user click on back button
=> Fix back button logic

composeApp/src/androidMain/kotlin/band/effective/office/elevator/App.android.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/components/SeatReservation.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStoreFactory.kt, mattermost-bot/src/main/java/band/effective/BotManager.kt, mattermost-bot/src/main/java/band/effective/Handler.kt, mattermost-bot/src/main/java/band/effective/core/RetrofitInit.kt
Fix pull up to refresh and date period on main screen
=> Date range on main screen

composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/BookingRepositoryImpl.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/bottomSheets/bookingSheet/bookAccept/store/BookAcceptStoreFactory.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/bottomSheets/bookingSheet/bookPeriod/store/BookPeriodStoreFactory.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/main/store/MainStoreFactory.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/utils/LocalDateTimeToUnix.kt
Fix date range input and minor fixes
=> Fix date range input

composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/di/DataModuleDI.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/domain/entity/BookingInteract.kt
Added a function, that sorts workspaces by first letter and last digit
=> add function for sort workspaces

tvApp/src/main/java/band/effective/office/tv/domain/use_cases/PhotoSynologyUseCase.kt, tvApp/src/main/java/band/effective/office/tv/repository/synology/impl/PhotoSynologyRepositoryImpl.kt
[~] Changed use case to return shuffled list with photos from album
=> Random photos from album

tvApp/src/main/java/band/effective/office/tv/screen/photo/BestPhotoScreen.kt, tvApp/src/main/java/band/effective/office/tv/screen/photo/components/PhotoUI.kt
[~] Just changed Content Scale type
=> Tv app Vertical photos

effectiveOfficeBackend/src/main/kotlin/office/effective/dto/BookingDTO.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/dto/WorkspaceResponseDTO.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/BookingDtoModelConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/routes/swagger/BookingSwagger.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/DI/WorkspaceDiModule.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/converters/WorkspaceDtoModelConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/facade/WorkspaceFacade.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/facade/WorkspaceFacadeV1.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/workspace/routes/swagger/WorkspaceSwagger.kt, effectiveOfficeBackend/src/test/kotlin/office/effective/workspace/WorkspaceFacadeTest.kt
Workspace DTO without "bookings" for api V0  + rename WorkspaceFacadeConverter to WorkspaceDtoModelConverter
=> [+] add workspace dto for api v0

build.gradle.kts, gradle/libs.versions.toml, tvApp/build.gradle.kts, tvApp/src/main/java/band/effective/office/tv/di/view_models/MessageViewModelModule.kt
Avif/Heic decoder plugin for coil
=> Tv app/feature/transecode heic format

tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/updateEvent/store/UpdateEventStoreFactory.kt
Booking button could be unlocked, when user selected date using arrows
=> Fix booking button when organizer wasn't selected

effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/DateExtensions.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/converters/GoogleCalendarConverter.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/BookingMeetingRepository.kt, effectiveOfficeBackend/src/main/kotlin/office/effective/features/booking/repository/BookingRegularRepository.kt
Fix date conversion which added/subtracted time offset without consideration for time zone.
=> backend: fix date conversion

tabletApp/features/core/src/commonMain/kotlin/band/effective/office/tablet/domain/model/RoomInfo.kt, tabletApp/features/domain/src/commonMain/kotlin/band/effective/office/tablet/domain/useCase/SelectRoomUseCase.kt, tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/mainScreen/MainComponent.kt, tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/mainScreen/store/MainFactory.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/fastEvent/FastEventComponent.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/fastEvent/FastEventView.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/fastEvent/store/FastEventStore.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/fastEvent/store/FastEventStoreFactory.kt, tabletApp/features/selectRoom/src/commonMain/kotlin/band/effective/office/tablet/ui/uiComponents/successBooking/SuccessFastSelectRoomView.kt
Was: We could quick book only room, that was selected. If that room busy, we had to select other room and book it.
Became: We can quick book even if we select busy room, but tablet will book nearby free room.
=> EO-628, TabletApp: Fix behavior fast booking

composeApp/src/commonMain/kotlin/band/effective/office/elevator/EffectiveDarkColors.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/Theme.kt
=> Mobile: compile error

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_phone/AuthorizationPhoneScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/employee/aboutEmployee/AboutEmployee.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/ProfileEditScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/mainProfile/ProfileScreen.kt, composeApp/src/commonMain/moko-resources/base/strings_ru.xml, composeApp/src/commonMain/moko-resources/en/strings_en.xml
Fix strings, navigation to profile and appbar on colleagues screen
=> EO-743, 745, 747

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/GoogleSignInButton.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_google/AuthorizationGoogleComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_google/AuthorizationGoogleScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_google/store/AuthorizationGoogleStore.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_google/store/AuthorizationGoogleStoreImpl.kt
Add progress indicator during logging in, fix files with button and entering process
=> EO-789: Fix auth google button

composeApp/src/commonMain/kotlin/band/effective/office/elevator/data/repository/ProfileRepositoryImpl.kt, composeApp/src/iosMain/kotlin/band/effective/office/elevator/expects/PlatformExpects.ios.kt
https://github.com/user-attachments/assets/3bd4fb9c-edf4-4f8d-8b03-0c05698f4afe
=> EO-814: fix data saving on profile screen

composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/AuthorizationComponent.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/store/AuthorizationStoreImpl.kt
=> 211: Bug double registration 

tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/mainScreen/MainComponent.kt, tabletApp/features/roomInfo/src/commonMain/kotlin/band/effective/office/tablet/ui/mainScreen/mainScreen/store/MainFactory.kt
In This PR, change get roomName and roomIndex for fix crash to select room in first start TabletApp.
=> TabletApp: Fix crash on first start

tvApp/src/main/java/band/effective/office/tv/screen/leaderIdEvents/LeaderIdEventsViewModel.kt
In This PR, add switch to first event when autoplay reaches the last element in events, in tvApp.
=> EO-767, tvApp: Add event looping

composeApp/src/commonMain/kotlin/band/effective/office/elevator/components/UserInfoTextField.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/authorization/authorization_phone/AuthorizationPhoneScreen.kt, composeApp/src/commonMain/kotlin/band/effective/office/elevator/ui/profile/editProfile/ProfileEditScreen.kt
Added phone number validation: automatic filtering of non-digit characters and a 10-digit length limit. Invalid input is now blocked.
=> mobile/EO-828: [~]Fix: Add input filtering for phone number field

backend/feature/booking/calendar/google/src/main/kotlin/band/effective/office/backend/feature/booking/calendar/google/GoogleCalendarProvider.kt, backend/feature/notifications/src/main/kotlin/band/effective/office/backend/feature/notifications/controller/NotificationDeduplicator.kt
- Implemented event deletion when all participants decline via `deleteEvent` method.
- Refactored `listEvents` to modularize request building and processing.
- Added `buildEventsRequest`, `processEvents`, and utility functions for better maintainability.
- Reduced notification deduplication TTL to 5 seconds for faster processing.
=> feat: enhance Google Calendar integration and optimize notifications

clients/tablet/core/ui/src/commonMain/kotlin/band/effective/office/tablet/core/ui/common/EventDurationView.kt
- Disable decrement button in EventDurationView when duration <= 15 minutes
=> fix: Prevent event duration below 15 minutes to avoid crash

clients/tablet/core/ui/src/commonMain/composeResources/values-ru/strings_ru.xml, clients/tablet/core/ui/src/commonMain/composeResources/values/strings.xml, clients/tablet/core/ui/src/commonMain/kotlin/band/effective/office/tablet/core/ui/common/EventDurationView.kt, clients/tablet/feature/bookingEditor/src/commonMain/composeResources/values-ru/strings_ru.xml, clients/tablet/feature/bookingEditor/src/commonMain/composeResources/values/strings.xml, clients/tablet/feature/main/src/commonMain/composeResources/values-ru/strings_ru.xml, clients/tablet/feature/main/src/commonMain/composeResources/values/strings.xml
- Correct English text for clarity and consistency
- Update Russian text for proper formatting
- Add space in time duration strings
=> feat: Update English and Russian text strings

README.md
- Removed unnecessary emoji from "Features Overview" heading.
- Clarified `.env` setup with an instruction to customize the file.
- Added a new "Run Clients" section with IDE-specific steps for Android and backend clients.
=> Docs: finalizing README 

backend/app/src/main/resources/application.yml, backend/feature/booking/core/src/main/kotlin/band/effective/office/backend/feature/booking/core/controller/BookingController.kt, backend/feature/booking/core/src/main/kotlin/band/effective/office/backend/feature/booking/core/dto/BookingDto.kt, backend/feature/booking/core/src/main/kotlin/band/effective/office/backend/feature/booking/core/dto/CreateUpdateBookingDto.kt, backend/feature/workspace/src/main/kotlin/band/effective/office/backend/feature/workspace/core/controller/WorkspaceController.kt
-Added server.forward-headers-strategy: FRAMEWORK to application.yml to ensure Spring Boot correctly handles X-Forwarded-* headers from the proxy server, fixing Swagger UI to display https instead of http for API endpoints
-Updated the Swagger docs. All the endpoints are now working and up-to-date.
=> Update Swagger documentation with latest API changes
